// js/cargos-data.js - Base de datos completa de perfiles de cargo NIVELIA S.A.S.
// Fuente: Documento NIV-ORG-001, Sección 8

const CARGOS_DATA = [
  // ============ NIVEL GOBIERNO Y DIRECCIÓN ============
  {
    codigo: "NIV-GOB-001", area: "Gobierno Corporativo", nivel: "Estratégico",
    cargo: "Junta Directiva", jefe: "No aplica; órgano superior de gobierno",
    proposito: "Establecer los lineamientos estratégicos de NIVELIA S.A.S., supervisar la gestión de la organización y realizar seguimiento al cumplimiento de los objetivos empresariales.",
    formacion: "Según perfil de los miembros y requisitos definidos por la organización.",
    formacionComp: "Gobierno corporativo, estrategia, finanzas, gestión de riesgos y dirección empresarial.",
    experiencia: "Experiencia relevante en dirección, gestión empresarial, ingeniería, tecnología, finanzas o áreas afines.",
    compTecnicas: "Gobierno corporativo, análisis financiero, gestión de riesgos, estrategia.",
    compComportamentales: "Liderazgo, criterio, integridad, pensamiento estratégico, imparcialidad.",
    funciones: ["Aprobar lineamientos estratégicos", "Supervisar la Gerencia", "Revisar resultados", "Evaluar riesgos", "Analizar crecimiento y sostenibilidad", "Aprobar decisiones corporativas relevantes"],
    responsabilidades: "Velar por la sostenibilidad de la organización y la adecuada orientación estratégica.",
    autoridad: "Aprobar decisiones estratégicas de su competencia y ejercer supervisión sobre la Gerencia General.",
    relInternas: "Gerencia General, Auditoría Interna, Direcciones.",
    relExternas: "Accionistas, aliados estratégicos, entidades relevantes y terceros institucionales.",
    indicadores: "Cumplimiento de objetivos estratégicos, crecimiento, sostenibilidad financiera, seguimiento de riesgos.",
    modalidad: "Ejercicio de funciones como órgano societario; no corresponde tratarlo como una modalidad laboral ordinaria."
  },
  {
    codigo: "NIV-GER-001", area: "Gerencia General", nivel: "Estratégico",
    cargo: "Gerente General", jefe: "Junta Directiva",
    proposito: "Dirigir integralmente NIVELIA S.A.S., asegurando el cumplimiento de la estrategia, sostenibilidad financiera, desarrollo de negocios y coordinación de las áreas.",
    formacion: "Ingeniería, Administración de Empresas, Ingeniería Industrial, Ingeniería Civil o profesión afín.",
    formacionComp: "Dirección empresarial, gestión financiera, estrategia, negociación y gestión de proyectos.",
    experiencia: "Mínimo 5 años en dirección empresarial, ingeniería, tecnología, infraestructura o negocios.",
    compTecnicas: "Planeación estratégica, gestión financiera, negociación, gestión de riesgos.",
    compComportamentales: "Liderazgo, comunicación, toma de decisiones, orientación a resultados, ética.",
    funciones: ["Dirigir la organización", "Implementar la estrategia", "Coordinar directores", "Aprobar presupuestos", "Representar la empresa", "Gestionar relaciones institucionales", "Evaluar desempeño", "Liderar decisiones estratégicas"],
    responsabilidades: "Cumplimiento de objetivos empresariales, recursos, resultados y representación institucional.",
    autoridad: "Toma de decisiones ejecutivas dentro de las facultades asignadas por la organización.",
    relInternas: "Junta Directiva, directores, auditoría, colaboradores.",
    relExternas: "Clientes, entidades públicas y privadas, aliados, proveedores y demás partes interesadas.",
    indicadores: "Cumplimiento estratégico, crecimiento de ingresos, rentabilidad, satisfacción de clientes, ejecución presupuestal.",
    modalidad: "Contrato laboral a término indefinido, como cargo permanente de dirección."
  },
  {
    codigo: "NIV-AUD-001", area: "Auditoría Interna", nivel: "Control",
    cargo: "Auditor Interno", jefe: "Junta Directiva",
    proposito: "Evaluar de manera independiente los controles, procesos, riesgos y cumplimiento de NIVELIA.",
    formacion: "Contaduría, Administración, Ingeniería Industrial o profesión afín.",
    formacionComp: "Auditoría, riesgos, control interno, calidad.",
    experiencia: "Experiencia en auditoría y control.",
    compTecnicas: "Auditoría, riesgos, control interno, análisis.",
    compComportamentales: "Independencia, objetividad, ética, criterio profesional.",
    funciones: ["Elaborar plan de auditoría", "Evaluar procesos", "Revisar controles", "Evaluar riesgos", "Emitir informes", "Hacer seguimiento a acciones"],
    responsabilidades: "Independencia y objetividad de las evaluaciones.",
    autoridad: "Solicitar información y evidencias necesarias para auditoría.",
    relInternas: "Junta Directiva, Gerencia y todas las áreas.",
    relExternas: "Auditores, asesores y organismos pertinentes.",
    indicadores: "Auditorías ejecutadas, hallazgos cerrados, acciones correctivas verificadas.",
    modalidad: "Contrato laboral a término indefinido, preservando independencia funcional."
  },
  // ============ DIRECTORES ============
  {
    codigo: "NIV-DIR-ING-001", area: "Ingeniería Civil e Infraestructura", nivel: "Directivo",
    cargo: "Director de Ingeniería Civil e Infraestructura", jefe: "Gerente General",
    proposito: "Dirigir los procesos de ingeniería e infraestructura, garantizando viabilidad técnica, calidad, seguridad y cumplimiento de requisitos.",
    formacion: "Ingeniería Civil.",
    formacionComp: "Estructuras, hidráulica, infraestructura urbana, gestión de proyectos, BIM/CAD.",
    experiencia: "3-5 años en infraestructura, diseño, construcción o interventoría.",
    compTecnicas: "Diseño, revisión técnica, coordinación de especialistas, gestión de calidad.",
    compComportamentales: "Liderazgo, análisis, planificación, comunicación, toma de decisiones.",
    funciones: ["Dirigir estudios", "Aprobar diseños", "Coordinar especialistas", "Supervisar ingeniería", "Gestionar riesgos", "Revisar documentación", "Apoyar propuestas técnicas"],
    responsabilidades: "Calidad y viabilidad técnica de los trabajos bajo su dirección.",
    autoridad: "Revisar y aprobar entregables técnicos dentro de su competencia.",
    relInternas: "Gerencia, Operaciones, Tecnología, Sostenibilidad, Comercial.",
    relExternas: "Clientes, consultores, proveedores, entidades técnicas.",
    indicadores: "Cumplimiento de entregables, reprocesos, no conformidades, cumplimiento de plazos.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-DIR-TI-001", area: "Tecnología e Innovación", nivel: "Directivo",
    cargo: "Director de Tecnología e Innovación", jefe: "Gerente General",
    proposito: "Dirigir la estrategia tecnológica y digital de NIVELIA.",
    formacion: "Ingeniería de Sistemas, Electrónica, Mecatrónica o afín.",
    formacionComp: "Arquitectura de software, automatización, IoT, ciberseguridad, gestión tecnológica.",
    experiencia: "3–5 años en tecnología, automatización, software o sistemas inteligentes.",
    compTecnicas: "Arquitectura tecnológica, software, automatización, IoT, integración.",
    compComportamentales: "Liderazgo, innovación, análisis, comunicación, gestión de equipos.",
    funciones: ["Definir arquitectura", "Coordinar software", "Dirigir automatización", "Gestionar IoT", "Supervisar integraciones", "Coordinar ciberseguridad", "Liderar innovación tecnológica"],
    responsabilidades: "Disponibilidad, seguridad, evolución y coherencia de la plataforma tecnológica.",
    autoridad: "Definir criterios y estándares tecnológicos.",
    relInternas: "Todas las direcciones.",
    relExternas: "Proveedores tecnológicos, aliados, consultores.",
    indicadores: "Disponibilidad de sistemas, incidentes tecnológicos, cumplimiento de desarrollos, proyectos tecnológicos implementados.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-DIR-AMB-001", area: "Sostenibilidad y Gestión Ambiental", nivel: "Directivo",
    cargo: "Director de Sostenibilidad y Gestión Ambiental", jefe: "Gerente General",
    proposito: "Dirigir la estrategia ambiental y de sostenibilidad de NIVELIA.",
    formacion: "Ingeniería Ambiental, Ingeniería Civil con formación ambiental o profesión afín.",
    formacionComp: "Gestión ambiental, sostenibilidad, gestión hídrica, energía, legislación ambiental.",
    experiencia: "3-5 años en gestión ambiental o sostenibilidad.",
    compTecnicas: "Evaluación de impactos, residuos, indicadores, gestión ambiental.",
    compComportamentales: "Liderazgo, responsabilidad, análisis, comunicación.",
    funciones: ["Definir objetivos ambientales", "Supervisar cumplimiento", "Gestionar residuos", "Coordinar gestión hídrica", "Supervisar indicadores", "Promover eficiencia energética"],
    responsabilidades: "Cumplimiento de objetivos y compromisos ambientales.",
    autoridad: "Establecer lineamientos ambientales dentro de su competencia.",
    relInternas: "Todas las direcciones, especialmente Ingeniería y Operaciones.",
    relExternas: "Autoridades, consultores, proveedores, comunidades.",
    indicadores: "Cumplimiento ambiental, residuos gestionados, consumo energético, consumo de agua.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-DIR-COM-001", area: "Comercial y Mercado", nivel: "Directivo",
    cargo: "Director Comercial y de Mercado", jefe: "Gerente General",
    proposito: "Dirigir la estrategia comercial y el desarrollo de mercados y clientes.",
    formacion: "Administración de Empresas, Mercadeo, Ingeniería Industrial o afín.",
    formacionComp: "Ventas B2B, contratación, negociación, marketing.",
    experiencia: "3-5 años en ventas, infraestructura, tecnología o servicios B2B.",
    compTecnicas: "Ventas, licitaciones, negociación, análisis de mercado.",
    compComportamentales: "Liderazgo, persuasión, comunicación, orientación al cliente.",
    funciones: ["Definir estrategia comercial", "Supervisar ventas", "Gestionar clientes estratégicos", "Aprobar propuestas", "Coordinar licitaciones", "Supervisar marketing"],
    responsabilidades: "Cumplimiento de objetivos comerciales y satisfacción de clientes.",
    autoridad: "Aprobar propuestas dentro de las facultades asignadas.",
    relInternas: "Gerencia, Ingeniería, Tecnología, Finanzas, Operaciones.",
    relExternas: "Clientes, entidades públicas y privadas, aliados y prospectos.",
    indicadores: "Ventas, oportunidades calificadas, tasa de conversión, satisfacción del cliente.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-DIR-ADM-001", area: "Administrativa y Financiera", nivel: "Directivo",
    cargo: "Director Administrativo y Financiero", jefe: "Gerente General",
    proposito: "Administrar los recursos financieros, administrativos y de talento humano de la organización.",
    formacion: "Contaduría, Administración Financiera, Administración de Empresas, Ingeniería Industrial o afín.",
    formacionComp: "Finanzas corporativas, talento humano, compras, gestión administrativa.",
    experiencia: "3-5 años.",
    compTecnicas: "Finanzas, contabilidad, presupuesto, talento humano, compras.",
    compComportamentales: "Organización, liderazgo, análisis, confidencialidad.",
    funciones: ["Gestionar presupuesto", "Flujo de caja", "Contabilidad", "Talento humano", "Compras", "Contratos", "Recursos administrativos"],
    responsabilidades: "Uso eficiente y controlado de recursos.",
    autoridad: "Aprobar gestiones administrativas y financieras dentro de sus atribuciones.",
    relInternas: "Todas las áreas.",
    relExternas: "Bancos, proveedores, entidades, asesores.",
    indicadores: "Cumplimiento presupuestal, flujo de caja, pagos, rotación, cobertura de vacantes.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-DIR-OPE-001", area: "Operaciones", nivel: "Directivo",
    cargo: "Director de Operaciones", jefe: "Gerente General",
    proposito: "Garantizar la ejecución eficiente de las operaciones, instalación, mantenimiento y soporte de las soluciones.",
    formacion: "Ingeniería Civil, Industrial, Mecánica o afín.",
    formacionComp: "Operaciones, mantenimiento, logística, gestión de proyectos.",
    experiencia: "3-5 años.",
    compTecnicas: "Planeación, instalación, mantenimiento, control operacional.",
    compComportamentales: "Liderazgo, organización, resolución de problemas.",
    funciones: ["Coordinar operaciones", "Asignar recursos", "Coordinar personal", "Supervisar instalaciones", "Controlar mantenimiento", "Gestionar incidentes"],
    responsabilidades: "Continuidad y eficiencia operacional.",
    autoridad: "Asignar recursos y coordinar personal operativo según las funciones delegadas.",
    relInternas: "Todas las áreas técnicas.",
    relExternas: "Contratistas, proveedores, clientes.",
    indicadores: "Cumplimiento operacional, disponibilidad, tiempos de respuesta, incidentes.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-DIR-INN-001", area: "Innovación y Desarrollo de Negocios", nivel: "Directivo",
    cargo: "Director de Innovación y Desarrollo de Negocios", jefe: "Gerente General",
    proposito: "Liderar el desarrollo de nuevas soluciones, oportunidades y alianzas que permitan ampliar el portafolio de NIVELIA.",
    formacion: "Ingeniería, Administración o profesión afín.",
    formacionComp: "Innovación, desarrollo de productos, inteligencia de negocios, emprendimiento.",
    experiencia: "3-5 años.",
    compTecnicas: "I+D, prototipado, análisis de mercado, innovación.",
    compComportamentales: "Creatividad, liderazgo, pensamiento estratégico.",
    funciones: ["Liderar I+D", "Identificar tecnologías", "Desarrollar prototipos", "Evaluar oportunidades", "Gestionar alianzas", "Analizar mercados"],
    responsabilidades: "Crecimiento y diversificación del portafolio.",
    autoridad: "Priorizar iniciativas de innovación dentro de los criterios aprobados.",
    relInternas: "Todas las direcciones.",
    relExternas: "Universidades, empresas tecnológicas, aliados e inversionistas.",
    indicadores: "Iniciativas de innovación, prototipos, nuevos productos, alianzas.",
    modalidad: "Contrato laboral a término indefinido."
  },
  // ============ INGENIERÍA ============
  {
    codigo: "NIV-ING-001", area: "Ingeniería Civil e Infraestructura", nivel: "Profesional",
    cargo: "Ingeniero Civil", jefe: "Director de Ingeniería Civil e Infraestructura",
    proposito: "Desarrollar estudios, diseños, análisis y actividades de apoyo técnico relacionadas con las soluciones de infraestructura desarrolladas por NIVELIA S.A.S.",
    formacion: "Profesional en Ingeniería Civil.",
    formacionComp: "Diseño de infraestructura, estructuras, hidráulica, herramientas CAD/BIM y gestión de proyectos.",
    experiencia: "Experiencia en diseño, construcción, supervisión, interventoría o consultoría de infraestructura.",
    compTecnicas: "Diseño de infraestructura, interpretación de planos, cálculos técnicos, especificaciones y herramientas de diseño.",
    compComportamentales: "Análisis, organización, responsabilidad, comunicación y trabajo en equipo.",
    funciones: ["Elaborar y revisar diseños", "Realizar cálculos", "Participar en estudios técnicos", "Apoyar supervisión", "Elaborar informes", "Verificar especificaciones", "Participar en reuniones interdisciplinarias"],
    responsabilidades: "Calidad y oportunidad de los entregables técnicos; cumplimiento de procedimientos; correcta gestión de la información técnica.",
    autoridad: "Emitir conceptos técnicos dentro de su competencia y solicitar información necesaria para desarrollar sus funciones.",
    relInternas: "Ingeniería, Operaciones, Tecnología, Sostenibilidad y Comercial.",
    relExternas: "Consultores, proveedores, contratistas y clientes cuando corresponda.",
    indicadores: "Cumplimiento de entregables; porcentaje de reprocesos; no conformidades; cumplimiento de plazos.",
    modalidad: "Contrato laboral a término indefinido para necesidades permanentes; otra modalidad laboral aplicable cuando la necesidad sea temporal y cumpla los requisitos correspondientes."
  },
  {
    codigo: "NIV-ING-002", area: "Ingeniería Civil e Infraestructura", nivel: "Profesional",
    cargo: "Ingeniero Hidráulico", jefe: "Director de Ingeniería Civil e Infraestructura",
    proposito: "Desarrollar estudios y análisis relacionados con aguas lluvias, drenaje, comportamiento hidráulico y gestión del recurso hídrico.",
    formacion: "Ingeniería Civil, Ingeniería Sanitaria o profesión afín con formación especializada en hidráulica.",
    formacionComp: "Hidrología, hidráulica urbana, drenaje, modelación y gestión de aguas lluvias.",
    experiencia: "Experiencia en estudios hidráulicos, drenaje urbano, hidrología o infraestructura relacionada con agua.",
    compTecnicas: "Modelación hidráulica, análisis de drenajes, hidrología, interpretación de información técnica y herramientas especializadas.",
    compComportamentales: "Pensamiento analítico, precisión, organización y comunicación técnica.",
    funciones: ["Analizar sistemas de drenaje", "Estudiar comportamiento de aguas lluvias", "Desarrollar modelos", "Evaluar alternativas", "Elaborar conceptos e informes técnicos"],
    responsabilidades: "Confiabilidad de los análisis hidráulicos y cumplimiento de requisitos técnicos y ambientales aplicables.",
    autoridad: "Emitir conceptos y recomendaciones técnicas dentro de su especialidad.",
    relInternas: "Ingeniería, Sostenibilidad, Operaciones e Innovación.",
    relExternas: "Consultores, especialistas, proveedores y entidades técnicas.",
    indicadores: "Entregables aprobados; reprocesos; cumplimiento de requisitos; cumplimiento de plazos.",
    modalidad: "Laboral para necesidades permanentes o contratación profesional especializada cuando exista una necesidad independiente y puntual."
  },
  {
    codigo: "NIV-ING-003", area: "Ingeniería Civil e Infraestructura", nivel: "Profesional",
    cargo: "Ingeniero Estructural", jefe: "Director de Ingeniería Civil e Infraestructura",
    proposito: "Analizar, diseñar y verificar sistemas estructurales asociados a las soluciones de infraestructura de NIVELIA.",
    formacion: "Ingeniería Civil.",
    formacionComp: "Ingeniería estructural, diseño sismorresistente, análisis estructural y modelación.",
    experiencia: "Experiencia en diseño, revisión o evaluación estructural.",
    compTecnicas: "Análisis estructural, cargas, dimensionamiento, modelación y especificaciones.",
    compComportamentales: "Rigurosidad, análisis, responsabilidad y trabajo interdisciplinario.",
    funciones: ["Realizar análisis estructural", "Desarrollar diseños", "Revisar materiales y elementos", "Verificar estabilidad", "Elaborar memorias y conceptos técnicos"],
    responsabilidades: "Seguridad, confiabilidad y calidad de los diseños estructurales.",
    autoridad: "Emitir conceptos estructurales dentro de su competencia profesional.",
    relInternas: "Ingeniería, Operaciones, Calidad y Tecnología.",
    relExternas: "Consultores y especialistas externos.",
    indicadores: "Reprocesos; no conformidades; entregables aprobados; cumplimiento de requisitos.",
    modalidad: "Laboral para necesidad permanente o contratación especializada según el alcance de la necesidad."
  },
  {
    codigo: "NIV-ING-004", area: "Ingeniería Civil e Infraestructura", nivel: "Profesional",
    cargo: "Ingeniero de Diseño", jefe: "Director de Ingeniería Civil e Infraestructura",
    proposito: "Desarrollar y documentar diseños técnicos integrando los requerimientos funcionales y de ingeniería.",
    formacion: "Ingeniería Civil, Mecánica, Industrial o profesión afín según el área de diseño.",
    formacionComp: "CAD/BIM, modelado, diseño técnico y gestión documental.",
    experiencia: "Experiencia en diseño técnico y elaboración de documentación de ingeniería.",
    compTecnicas: "Modelado, planos, especificaciones, diseño y documentación.",
    compComportamentales: "Creatividad, precisión, organización y trabajo en equipo.",
    funciones: ["Desarrollar diseños", "Elaborar planos", "Actualizar documentación", "Coordinar componentes interdisciplinarios", "Incorporar observaciones técnicas"],
    responsabilidades: "Exactitud y trazabilidad de los documentos de diseño.",
    autoridad: "Proponer soluciones de diseño dentro de su competencia.",
    relInternas: "Ingeniería, Tecnología, Operaciones y Sostenibilidad.",
    relExternas: "Proveedores y consultores técnicos cuando corresponda.",
    indicadores: "Entregables aprobados; errores de diseño; reprocesos; cumplimiento de tiempos.",
    modalidad: "Contrato laboral a término indefinido para necesidad permanente."
  },
  {
    codigo: "NIV-ING-005", area: "Ingeniería Civil e Infraestructura", nivel: "Profesional",
    cargo: "Arquitecto", jefe: "Director de Ingeniería Civil e Infraestructura",
    proposito: "Integrar criterios arquitectónicos, funcionales, espaciales y de accesibilidad en las soluciones desarrolladas por NIVELIA.",
    formacion: "Arquitectura.",
    formacionComp: "Accesibilidad, diseño urbano, diseño inclusivo y herramientas CAD/BIM.",
    experiencia: "Experiencia en diseño arquitectónico, urbano o de infraestructura.",
    compTecnicas: "Diseño espacial, accesibilidad, interpretación normativa y representación gráfica.",
    compComportamentales: "Creatividad, análisis, comunicación y orientación al usuario.",
    funciones: ["Desarrollar propuestas arquitectónicas", "Integrar accesibilidad", "Revisar funcionalidad", "Coordinar diseños interdisciplinarios"],
    responsabilidades: "Coherencia funcional, arquitectónica y de accesibilidad de sus entregables.",
    autoridad: "Emitir recomendaciones de diseño dentro de su competencia.",
    relInternas: "Ingeniería, Sostenibilidad, Tecnología y Operaciones.",
    relExternas: "Consultores, clientes y entidades cuando corresponda.",
    indicadores: "Diseños aprobados; cumplimiento de requisitos; reprocesos.",
    modalidad: "Laboral para necesidades permanentes o contratación especializada según necesidad."
  },
  {
    codigo: "NIV-ING-006", area: "Ingeniería Civil e Infraestructura", nivel: "Profesional/Técnico",
    cargo: "Topógrafo", jefe: "Director de Ingeniería Civil e Infraestructura",
    proposito: "Proporcionar información topográfica precisa para estudios, diseños, supervisión y control geométrico.",
    formacion: "Tecnología o formación profesional en Topografía, de acuerdo con los requerimientos del cargo.",
    formacionComp: "Georreferenciación, levantamientos, sistemas GNSS y software especializado.",
    experiencia: "Experiencia en levantamientos topográficos y control geométrico de proyectos.",
    compTecnicas: "Levantamientos, medición, georreferenciación, procesamiento de datos.",
    compComportamentales: "Precisión, orden, concentración, responsabilidad.",
    funciones: ["Realizar levantamientos", "Efectuar mediciones", "Procesar información", "Apoyar control geométrico", "Elaborar registros topográficos"],
    responsabilidades: "Exactitud y trazabilidad de la información levantada.",
    autoridad: "Reportar inconsistencias y condiciones que puedan afectar los estudios.",
    relInternas: "Ingeniería y Operaciones.",
    relExternas: "Contratistas, proveedores y equipos de campo.",
    indicadores: "Precisión de levantamientos; reprocesos; cumplimiento de programación.",
    modalidad: "Laboral o contratación especializada según la frecuencia y naturaleza de los levantamientos."
  },
  // ============ TECNOLOGÍA ============
  {
    codigo: "NIV-TI-001", area: "Tecnología e Innovación", nivel: "Profesional",
    cargo: "Ingeniero de Sistemas", jefe: "Director de Tecnología e Innovación",
    proposito: "Diseñar, implementar y mantener componentes de arquitectura, sistemas y plataformas tecnológicas.",
    formacion: "Ingeniería de Sistemas o afín.",
    formacionComp: "Arquitectura de software, bases de datos, nube y ciberseguridad.",
    experiencia: "Experiencia en desarrollo o arquitectura de sistemas.",
    compTecnicas: "Sistemas, arquitectura, integración, bases de datos y plataformas.",
    compComportamentales: "Análisis, innovación, organización, comunicación.",
    funciones: ["Diseñar arquitectura", "Desarrollar integraciones", "Analizar requerimientos", "Documentar soluciones", "Apoyar soporte tecnológico"],
    responsabilidades: "Disponibilidad, calidad y coherencia técnica de las soluciones asignadas.",
    autoridad: "Proponer decisiones técnicas y arquitectónicas dentro de su competencia.",
    relInternas: "Tecnología, Ingeniería, Operaciones e Innovación.",
    relExternas: "Proveedores y especialistas tecnológicos.",
    indicadores: "Disponibilidad; incidentes; cumplimiento de entregables; reprocesos.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-TI-002", area: "Tecnología e Innovación", nivel: "Profesional",
    cargo: "Ingeniero Electrónico", jefe: "Director de Tecnología e Innovación",
    proposito: "Diseñar, integrar y verificar componentes electrónicos, sensores y sistemas de control.",
    formacion: "Ingeniería Electrónica.",
    formacionComp: "Sistemas embebidos, instrumentación, control y comunicaciones.",
    experiencia: "Experiencia en electrónica, automatización o sistemas de control.",
    compTecnicas: "Circuitos, sensores, controladores, pruebas y diagnóstico.",
    compComportamentales: "Precisión, análisis, innovación y trabajo en equipo.",
    funciones: ["Diseñar circuitos", "Seleccionar componentes", "Integrar sensores", "Ejecutar pruebas", "Documentar soluciones"],
    responsabilidades: "Confiabilidad de los sistemas electrónicos desarrollados.",
    autoridad: "Recomendar componentes y soluciones técnicas.",
    relInternas: "Tecnología, Ingeniería, Operaciones.",
    relExternas: "Proveedores tecnológicos y especialistas.",
    indicadores: "Fallas; pruebas aprobadas; cumplimiento técnico.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-TI-003", area: "Tecnología e Innovación", nivel: "Profesional",
    cargo: "Ingeniero Mecatrónico", jefe: "Director de Tecnología e Innovación",
    proposito: "Integrar sistemas mecánicos, electrónicos y de automatización para las soluciones de NIVELIA.",
    formacion: "Ingeniería Mecatrónica.",
    formacionComp: "Automatización, control, robótica y sistemas electromecánicos.",
    experiencia: "Experiencia en automatización y sistemas mecatrónicos.",
    compTecnicas: "Actuadores, control, automatización, integración.",
    compComportamentales: "Análisis, innovación, resolución de problemas.",
    funciones: ["Diseñar sistemas de automatización", "Integrar actuadores", "Realizar pruebas", "Diagnosticar fallas"],
    responsabilidades: "Desempeño y confiabilidad de los sistemas mecatrónicos.",
    autoridad: "Proponer ajustes técnicos dentro de su competencia.",
    relInternas: "Tecnología, Ingeniería, Operaciones.",
    relExternas: "Proveedores especializados.",
    indicadores: "Disponibilidad; fallas; pruebas aprobadas; tiempos de solución.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-TI-004", area: "Tecnología e Innovación", nivel: "Profesional",
    cargo: "Desarrollador de Software", jefe: "Director de Tecnología e Innovación",
    proposito: "Desarrollar, probar, documentar y mantener las aplicaciones y plataformas digitales de NIVELIA.",
    formacion: "Ingeniería de Sistemas, Software o formación afín.",
    formacionComp: "Programación, bases de datos, APIs, control de versiones y pruebas.",
    experiencia: "Experiencia en desarrollo de software.",
    compTecnicas: "Programación, bases de datos, pruebas, versionamiento.",
    compComportamentales: "Análisis, aprendizaje, organización y resolución de problemas.",
    funciones: ["Analizar requerimientos", "Desarrollar funcionalidades", "Realizar pruebas", "Documentar", "Corregir incidencias", "Mantener aplicaciones"],
    responsabilidades: "Calidad y estabilidad del código desarrollado.",
    autoridad: "Proponer soluciones técnicas y mejoras dentro de los estándares definidos.",
    relInternas: "Tecnología, Ingeniería, Operaciones.",
    relExternas: "Proveedores de tecnología cuando corresponda.",
    indicadores: "Entregas; defectos; incidencias; disponibilidad.",
    modalidad: "Contrato laboral a término indefinido."
  },
  {
    codigo: "NIV-TI-005", area: "Tecnología e Innovación", nivel: "Profesional Especialista",
    cargo: "Especialista IoT", jefe: "Director de Tecnología e Innovación",
    proposito: "Diseñar e integrar soluciones de sensores, conectividad, monitoreo y transmisión de datos.",
    formacion: "Ingeniería de Sistemas, Electrónica, Telecomunicaciones o afín.",
    formacionComp: "IoT, redes, sensores, plataformas en la nube y protocolos de comunicación.",
    experiencia: "Experiencia en sistemas IoT o tecnologías de monitoreo.",
    compTecnicas: "Sensores, conectividad, protocolos, plataformas IoT.",
    compComportamentales: "Innovación, análisis, comunicación.",
    funciones: ["Seleccionar sensores", "Configurar dispositivos", "Integrar conectividad", "Validar transmisión", "Desarrollar monitoreo"],
    responsabilidades: "Disponibilidad y confiabilidad de los sistemas IoT.",
    autoridad: "Recomendar tecnologías y arquitecturas IoT.",
    relInternas: "Tecnología, Ingeniería, Operaciones.",
    relExternas: "Proveedores tecnológicos y especialistas.",
    indicadores: "Disponibilidad de dispositivos; datos transmitidos; incidencias.",
    modalidad: "Laboral para funciones permanentes o contratación profesional especializada cuando la necesidad sea independiente y puntual."
  },
  {
    codigo: "NIV-TI-006", area: "Tecnología e Innovación", nivel: "Profesional",
    cargo: "Analista de Datos", jefe: "Director de Tecnología e Innovación",
    proposito: "Analizar información empresarial y operativa para apoyar la toma de decisiones.",
    formacion: "Ingeniería de Sistemas, Estadística, Ciencia de Datos o afín.",
    formacionComp: "Analítica, bases de datos, visualización y BI.",
    experiencia: "Experiencia en análisis y visualización de datos.",
    compTecnicas: "SQL, análisis, indicadores, visualización y calidad de datos.",
    compComportamentales: "Pensamiento analítico, orden y comunicación.",
    funciones: ["Procesar datos", "Generar indicadores", "Elaborar reportes", "Detectar tendencias", "Validar calidad de información"],
    responsabilidades: "Exactitud y oportunidad de los análisis.",
    autoridad: "Proponer indicadores y análisis de acuerdo con los requerimientos del negocio.",
    relInternas: "Tecnología, Comercial, Finanzas, Operaciones.",
    relExternas: "Proveedores de soluciones analíticas cuando corresponda.",
    indicadores: "Calidad de datos; tiempo de generación de informes; entregables.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-TI-007", area: "Tecnología e Innovación", nivel: "Profesional Especialista",
    cargo: "Especialista en Ciberseguridad", jefe: "Director de Tecnología e Innovación",
    proposito: "Proteger los sistemas, redes, dispositivos e información tecnológica de NIVELIA.",
    formacion: "Ingeniería de Sistemas, Electrónica o afín.",
    formacionComp: "Ciberseguridad, redes, gestión de vulnerabilidades y respuesta a incidentes.",
    experiencia: "Experiencia en seguridad de la información o ciberseguridad.",
    compTecnicas: "Gestión de accesos, vulnerabilidades, monitoreo e incidentes.",
    compComportamentales: "Confidencialidad, análisis, criterio y responsabilidad.",
    funciones: ["Gestionar accesos", "Identificar vulnerabilidades", "Monitorear eventos", "Responder a incidentes", "Apoyar evaluaciones de seguridad"],
    responsabilidades: "Protección y confidencialidad de los activos tecnológicos bajo su alcance.",
    autoridad: "Recomendar controles y escalar incidentes críticos.",
    relInternas: "Tecnología, Gerencia y todas las áreas usuarias.",
    relExternas: "Proveedores y especialistas de seguridad.",
    indicadores: "Incidentes; vulnerabilidades gestionadas; cumplimiento de controles.",
    modalidad: "Laboral para funciones permanentes o contratación especializada para servicios independientes."
  },
  {
    codigo: "NIV-TI-008", area: "Tecnología e Innovación", nivel: "Técnico",
    cargo: "Técnico de Soporte TI", jefe: "Director de Tecnología e Innovación",
    proposito: "Atender incidentes, requerimientos y soporte básico de infraestructura y equipos tecnológicos.",
    formacion: "Técnico o tecnólogo en Sistemas, Redes o afín.",
    formacionComp: "Soporte, redes, mantenimiento y seguridad básica.",
    experiencia: "Experiencia en soporte técnico.",
    compTecnicas: "Hardware, software, redes, mantenimiento y soporte.",
    compComportamentales: "Servicio, paciencia, comunicación y organización.",
    funciones: ["Atender usuarios", "Instalar equipos", "Diagnosticar incidentes", "Mantener inventarios", "Escalar problemas"],
    responsabilidades: "Continuidad del soporte tecnológico de primer nivel.",
    autoridad: "Escalar incidentes según prioridad y procedimiento.",
    relInternas: "Todas las áreas.",
    relExternas: "Proveedores TI.",
    indicadores: "Tiempo de respuesta; incidentes resueltos; satisfacción del usuario.",
    modalidad: "Laboral a término indefinido."
  },
  // ============ SOSTENIBILIDAD ============
  {
    codigo: "NIV-AMB-001", area: "Sostenibilidad y Gestión Ambiental", nivel: "Profesional",
    cargo: "Ingeniero Ambiental", jefe: "Director de Sostenibilidad y Gestión Ambiental",
    proposito: "Gestionar aspectos e impactos ambientales asociados a las operaciones y soluciones de NIVELIA.",
    formacion: "Ingeniería Ambiental.",
    formacionComp: "Gestión ambiental, residuos, sostenibilidad y normativa aplicable.",
    experiencia: "Experiencia en gestión ambiental.",
    compTecnicas: "Evaluación de impactos, residuos, indicadores y gestión ambiental.",
    compComportamentales: "Responsabilidad, análisis y trabajo en equipo.",
    funciones: ["Evaluar impactos", "Gestionar residuos", "Realizar seguimiento ambiental", "Elaborar informes", "Apoyar cumplimiento de requisitos"],
    responsabilidades: "Seguimiento a compromisos ambientales.",
    autoridad: "Recomendar medidas preventivas y correctivas ambientales.",
    relInternas: "Sostenibilidad, Ingeniería y Operaciones.",
    relExternas: "Consultores, proveedores y autoridades cuando corresponda.",
    indicadores: "Cumplimiento ambiental; residuos gestionados; hallazgos.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-AMB-002", area: "Sostenibilidad y Gestión Ambiental", nivel: "Profesional Especialista",
    cargo: "Especialista en Gestión Hídrica", jefe: "Director de Sostenibilidad y Gestión Ambiental",
    proposito: "Analizar y promover estrategias relacionadas con gestión del agua, drenaje y resiliencia hídrica.",
    formacion: "Ingeniería Civil, Ambiental, Sanitaria o profesión afín.",
    formacionComp: "Gestión hídrica, hidrología, drenaje y sostenibilidad.",
    experiencia: "Experiencia en gestión de recursos hídricos o infraestructura hidráulica.",
    compTecnicas: "Análisis hídrico, indicadores, gestión de riesgos.",
    compComportamentales: "Análisis, precisión y responsabilidad.",
    funciones: ["Evaluar riesgos hídricos", "Apoyar estudios", "Desarrollar estrategias", "Elaborar informes", "Proponer medidas"],
    responsabilidades: "Calidad de análisis y recomendaciones hídricas.",
    autoridad: "Emitir conceptos dentro de su especialidad.",
    relInternas: "Sostenibilidad, Ingeniería, Operaciones.",
    relExternas: "Consultores y entidades especializadas.",
    indicadores: "Estudios aprobados; recomendaciones implementadas; cumplimiento.",
    modalidad: "Laboral o contratación especializada según necesidad."
  },
  {
    codigo: "NIV-AMB-003", area: "Sostenibilidad y Gestión Ambiental", nivel: "Profesional",
    cargo: "Gestor de Sostenibilidad", jefe: "Director de Sostenibilidad y Gestión Ambiental",
    proposito: "Coordinar iniciativas, indicadores y acciones relacionadas con sostenibilidad.",
    formacion: "Ingeniería Ambiental, Administración, Ingeniería Industrial o afín.",
    formacionComp: "Sostenibilidad, economía circular, indicadores ESG y gestión ambiental.",
    experiencia: "Experiencia en sostenibilidad o gestión ambiental.",
    compTecnicas: "Indicadores, reportes, gestión de recursos y sostenibilidad.",
    compComportamentales: "Organización, comunicación y responsabilidad.",
    funciones: ["Gestionar indicadores", "Apoyar programas ambientales", "Coordinar iniciativas de eficiencia y economía circular", "Elaborar reportes"],
    responsabilidades: "Calidad y oportunidad de la información de sostenibilidad.",
    autoridad: "Proponer iniciativas de mejora ambiental.",
    relInternas: "Todas las direcciones.",
    relExternas: "Proveedores, consultores y aliados.",
    indicadores: "Cumplimiento de metas; reportes; iniciativas implementadas.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-SST-001", area: "Administrativa y Financiera / SST", nivel: "Profesional",
    cargo: "Profesional SST", jefe: "Director Administrativo y Financiero",
    proposito: "Coordinar actividades de prevención, gestión de peligros y promoción de condiciones seguras de trabajo.",
    formacion: "Profesional con formación y requisitos aplicables en Seguridad y Salud en el Trabajo.",
    formacionComp: "Gestión de riesgos, emergencias, investigación de incidentes.",
    experiencia: "Experiencia en SST en ambientes administrativos y/o operativos.",
    compTecnicas: "Identificación de peligros, evaluación de riesgos, inspecciones, capacitación.",
    compComportamentales: "Liderazgo, comunicación, prevención, responsabilidad.",
    funciones: ["Identificar riesgos", "Realizar inspecciones", "Apoyar capacitaciones", "Hacer seguimiento a controles", "Investigar incidentes"],
    responsabilidades: "Seguimiento al cumplimiento de controles SST dentro de su ámbito.",
    autoridad: "Recomendar medidas preventivas y escalar condiciones inseguras.",
    relInternas: "Todas las áreas, especialmente Operaciones.",
    relExternas: "ARL, proveedores y especialistas.",
    indicadores: "Accidentes; incidentes; inspecciones; capacitación; acciones correctivas.",
    modalidad: "Laboral o modalidad que corresponda según la estructura organizacional y requisitos aplicables."
  },
  // ============ COMERCIAL ============
  {
    codigo: "NIV-COM-001", area: "Comercial y Mercado", nivel: "Profesional",
    cargo: "Ejecutivo Comercial", jefe: "Director Comercial y de Mercado",
    proposito: "Desarrollar oportunidades de negocio y mantener relaciones comerciales con clientes y prospectos.",
    formacion: "Administración, Mercadeo, Ingeniería o profesión afín.",
    formacionComp: "Ventas B2B, negociación y contratación.",
    experiencia: "Experiencia comercial en servicios, ingeniería o tecnología.",
    compTecnicas: "Ventas consultivas, negociación, CRM, seguimiento comercial.",
    compComportamentales: "Comunicación, persuasión, orientación al cliente y resultados.",
    funciones: ["Prospectar", "Presentar soluciones", "Elaborar oportunidades", "Negociar", "Hacer seguimiento y gestionar relaciones"],
    responsabilidades: "Cumplimiento de metas comerciales y calidad del servicio al cliente.",
    autoridad: "Gestionar oportunidades dentro de los lineamientos establecidos.",
    relInternas: "Comercial, Ingeniería, Tecnología, Finanzas y Operaciones.",
    relExternas: "Clientes, prospectos y aliados.",
    indicadores: "Oportunidades; tasa de conversión; ventas; satisfacción del cliente.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-COM-002", area: "Comercial y Mercado", nivel: "Profesional",
    cargo: "Analista de Mercado", jefe: "Director Comercial y de Mercado",
    proposito: "Generar información sobre mercados, clientes, tendencias y competencia para apoyar decisiones comerciales.",
    formacion: "Mercadeo, Administración, Economía, Ingeniería Industrial o afín.",
    formacionComp: "Investigación de mercados, análisis de datos y BI.",
    experiencia: "Experiencia en investigación o inteligencia de mercados.",
    compTecnicas: "Investigación, análisis competitivo, indicadores y reportes.",
    compComportamentales: "Análisis, curiosidad, organización y comunicación.",
    funciones: ["Investigar mercados", "Analizar competencia", "Identificar oportunidades", "Elaborar informes", "Apoyar estrategia comercial"],
    responsabilidades: "Confiabilidad de la información utilizada en decisiones comerciales.",
    autoridad: "Proponer hallazgos y oportunidades.",
    relInternas: "Comercial, Innovación, Dirección General.",
    relExternas: "Fuentes de información, aliados y consultores.",
    indicadores: "Estudios realizados; oportunidades identificadas; entregables.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-COM-003", area: "Comercial y Mercado", nivel: "Profesional Especialista",
    cargo: "Especialista en Licitaciones", jefe: "Director Comercial y de Mercado",
    proposito: "Coordinar la preparación y presentación de ofertas en procesos de contratación y licitación.",
    formacion: "Administración, Derecho, Ingeniería o afín.",
    formacionComp: "Contratación, licitaciones, gestión documental y elaboración de propuestas.",
    experiencia: "Experiencia en licitaciones y contratación.",
    compTecnicas: "Revisión de pliegos, documentación, cronogramas y requisitos.",
    compComportamentales: "Organización, atención al detalle, gestión del tiempo.",
    funciones: ["Identificar oportunidades", "Revisar requisitos", "Coordinar documentos", "Preparar ofertas", "Controlar fechas y entregas"],
    responsabilidades: "Integridad y oportunidad documental de las ofertas.",
    autoridad: "Solicitar información necesaria a las áreas participantes.",
    relInternas: "Comercial, Jurídica, Ingeniería, Finanzas y Operaciones.",
    relExternas: "Entidades contratantes y aliados.",
    indicadores: "Ofertas presentadas; cumplimiento documental; oportunidades adjudicadas.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-COM-004", area: "Comercial y Mercado", nivel: "Profesional",
    cargo: "Profesional de Marketing y Comunicaciones", jefe: "Director Comercial y de Mercado",
    proposito: "Fortalecer el posicionamiento, identidad y comunicación de NIVELIA.",
    formacion: "Marketing, Comunicación, Publicidad o afín.",
    formacionComp: "Marketing digital, branding, contenidos y analítica.",
    experiencia: "Experiencia en marketing y comunicaciones corporativas.",
    compTecnicas: "Estrategia digital, contenidos, marca y analítica.",
    compComportamentales: "Creatividad, comunicación, organización.",
    funciones: ["Diseñar campañas", "Desarrollar contenidos", "Gestionar comunicación corporativa", "Apoyar eventos y posicionamiento"],
    responsabilidades: "Coherencia de la identidad y comunicaciones de NIVELIA.",
    autoridad: "Proponer campañas y contenidos dentro de lineamientos corporativos.",
    relInternas: "Comercial, Innovación, Gerencia.",
    relExternas: "Agencias, medios y aliados.",
    indicadores: "Alcance; interacción; campañas ejecutadas; posicionamiento.",
    modalidad: "Laboral a término indefinido."
  },
  // ============ ADMINISTRATIVA ============
  {
    codigo: "NIV-ADM-001", area: "Administrativa y Financiera", nivel: "Profesional",
    cargo: "Contador Público", jefe: "Director Administrativo y Financiero",
    proposito: "Administrar y controlar la información contable y financiera de la organización.",
    formacion: "Contaduría Pública.",
    formacionComp: "Tributación, NIIF, herramientas contables y auditoría.",
    experiencia: "Experiencia en contabilidad empresarial.",
    compTecnicas: "Registros, cierres, impuestos, estados financieros, facturación.",
    compComportamentales: "Exactitud, confidencialidad, organización.",
    funciones: ["Registrar operaciones", "Preparar información financiera", "Apoyar obligaciones tributarias", "Realizar cierres", "Controlar documentación"],
    responsabilidades: "Integridad y oportunidad de la información contable.",
    autoridad: "Emitir conceptos contables dentro de su competencia.",
    relInternas: "Finanzas, Compras, Comercial, Gerencia.",
    relExternas: "Bancos, proveedores, entidades y asesores.",
    indicadores: "Cierres oportunos; errores contables; cumplimiento de obligaciones.",
    modalidad: "Laboral cuando exista función permanente y subordinada; prestación profesional únicamente cuando exista verdadera independencia."
  },
  {
    codigo: "NIV-ADM-002", area: "Administrativa y Financiera", nivel: "Profesional",
    cargo: "Analista Financiero", jefe: "Director Administrativo y Financiero",
    proposito: "Analizar información financiera y apoyar la planeación económica de NIVELIA.",
    formacion: "Finanzas, Economía, Administración, Ingeniería Industrial o afín.",
    formacionComp: "Finanzas corporativas, presupuestos, costos y análisis financiero.",
    experiencia: "Experiencia en análisis financiero o presupuestal.",
    compTecnicas: "Presupuesto, costos, flujo de caja, análisis de resultados.",
    compComportamentales: "Análisis, organización, confidencialidad.",
    funciones: ["Elaborar presupuestos", "Analizar costos", "Proyectar flujo de caja", "Generar informes", "Apoyar decisiones financieras"],
    responsabilidades: "Calidad y oportunidad de los análisis financieros.",
    autoridad: "Proponer escenarios y recomendaciones financieras.",
    relInternas: "Finanzas, Gerencia y todas las direcciones.",
    relExternas: "Entidades financieras y proveedores cuando corresponda.",
    indicadores: "Exactitud de proyecciones; cumplimiento presupuestal; tiempos de reporte.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-TH-001", area: "Administrativa y Financiera", nivel: "Profesional",
    cargo: "Profesional de Talento Humano", jefe: "Director Administrativo y Financiero",
    proposito: "Gestionar los procesos de talento humano de NIVELIA desde la planeación hasta el desarrollo y bienestar.",
    formacion: "Psicología, Administración, Gestión Humana o afín.",
    formacionComp: "Selección, legislación laboral, nómina, bienestar y evaluación.",
    experiencia: "Experiencia en procesos de talento humano.",
    compTecnicas: "Selección, contratación, capacitación, bienestar, evaluación.",
    compComportamentales: "Empatía, confidencialidad, organización, comunicación.",
    funciones: ["Gestionar selección", "Apoyar contratación", "Coordinar inducción", "Capacitar", "Administrar desempeño y bienestar"],
    responsabilidades: "Calidad y confidencialidad de la gestión de personas.",
    autoridad: "Gestionar procesos de selección y desarrollo conforme a políticas y procedimientos.",
    relInternas: "Todas las áreas.",
    relExternas: "Proveedores de formación y servicios de talento humano.",
    indicadores: "Rotación; cobertura de vacantes; capacitación; satisfacción interna.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-004", area: "Administrativa y Financiera", nivel: "Profesional",
    cargo: "Asesor Jurídico", jefe: "Director Administrativo y Financiero",
    proposito: "Brindar asesoría jurídica para reducir riesgos legales y apoyar la gestión contractual y corporativa.",
    formacion: "Derecho.",
    formacionComp: "Contratación, derecho empresarial, propiedad intelectual y cumplimiento.",
    experiencia: "Experiencia en asesoría jurídica empresarial o contractual.",
    compTecnicas: "Contratos, legislación, análisis jurídico, gestión documental.",
    compComportamentales: "Análisis, criterio, confidencialidad, negociación.",
    funciones: ["Revisar contratos", "Emitir conceptos", "Apoyar cumplimiento", "Gestionar asuntos legales", "Revisar propiedad intelectual"],
    responsabilidades: "Calidad de la asesoría y gestión de riesgos jurídicos.",
    autoridad: "Emitir conceptos jurídicos y formular recomendaciones.",
    relInternas: "Gerencia, Comercial, Compras, Finanzas y Operaciones.",
    relExternas: "Abogados externos, clientes, proveedores y autoridades.",
    indicadores: "Contratos revisados; tiempos de respuesta; contingencias identificadas.",
    modalidad: "Laboral si existe función permanente subordinada o prestación de servicios profesionales si se trata de una consultoría verdaderamente independiente."
  },
  {
    codigo: "NIV-ADM-005", area: "Administrativa y Financiera", nivel: "Profesional",
    cargo: "Analista de Compras", jefe: "Director Administrativo y Financiero",
    proposito: "Gestionar las adquisiciones y la relación operativa con proveedores bajo criterios de eficiencia, calidad y transparencia.",
    formacion: "Administración, Ingeniería Industrial, Logística o afín.",
    formacionComp: "Compras, negociación, inventarios y gestión de proveedores.",
    experiencia: "Experiencia en compras o abastecimiento.",
    compTecnicas: "Cotizaciones, análisis de ofertas, negociación y seguimiento.",
    compComportamentales: "Organización, negociación, responsabilidad.",
    funciones: ["Solicitar cotizaciones", "Evaluar ofertas", "Elaborar órdenes", "Hacer seguimiento", "Actualizar información de proveedores"],
    responsabilidades: "Trazabilidad y oportunidad de las adquisiciones.",
    autoridad: "Gestionar cotizaciones y propuestas dentro de los procedimientos establecidos.",
    relInternas: "Todas las áreas solicitantes.",
    relExternas: "Proveedores y contratistas.",
    indicadores: "Tiempo de compra; cumplimiento de proveedores; ahorros; no conformidades.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-006", area: "Administrativa y Financiera", nivel: "Administrativo",
    cargo: "Auxiliar Administrativo", jefe: "Profesional / responsable administrativo",
    proposito: "Apoyar las actividades administrativas y documentales de NIVELIA.",
    formacion: "Técnico o tecnólogo administrativo.",
    formacionComp: "Ofimática y gestión documental.",
    experiencia: "Experiencia en apoyo administrativo.",
    compTecnicas: "Archivo, ofimática, registros y documentación.",
    compComportamentales: "Organización, servicio y confidencialidad.",
    funciones: ["Gestionar archivo", "Elaborar registros", "Apoyar compras", "Manejar documentación y correspondencia"],
    responsabilidades: "Exactitud y organización de los registros.",
    autoridad: "Gestionar documentos dentro de procedimientos establecidos.",
    relInternas: "Todas las áreas administrativas.",
    relExternas: "Proveedores y visitantes cuando corresponda.",
    indicadores: "Exactitud documental; tiempos de respuesta; registros completos.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-007", area: "Administrativa y Financiera", nivel: "Administrativo",
    cargo: "Auxiliar Contable", jefe: "Contador Público",
    proposito: "Apoyar el registro y organización de la información contable.",
    formacion: "Técnico o tecnólogo contable.",
    formacionComp: "Software contable y Excel.",
    experiencia: "Experiencia en procesos contables básicos.",
    compTecnicas: "Registros, conciliaciones, facturación y archivo.",
    compComportamentales: "Exactitud, confidencialidad, orden.",
    funciones: ["Registrar información", "Apoyar conciliaciones", "Organizar soportes", "Apoyar facturación"],
    responsabilidades: "Calidad y disponibilidad de la documentación contable.",
    autoridad: "Gestionar registros dentro de los procedimientos definidos.",
    relInternas: "Finanzas, Compras, Comercial.",
    relExternas: "Proveedores cuando corresponda.",
    indicadores: "Errores; documentos procesados; tiempos de cierre.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-008", area: "Administrativa y Financiera", nivel: "Administrativo",
    cargo: "Auxiliar de Compras", jefe: "Analista / Profesional de Compras",
    proposito: "Apoyar las actividades administrativas y documentales del proceso de compras.",
    formacion: "Técnico administrativo, logística o afín.",
    formacionComp: "Compras y herramientas ofimáticas.",
    experiencia: "Experiencia en apoyo administrativo o compras.",
    compTecnicas: "Cotizaciones, registros, seguimiento y archivo.",
    compComportamentales: "Orden, atención al detalle, responsabilidad.",
    funciones: ["Solicitar cotizaciones", "Organizar ofertas", "Actualizar registros", "Hacer seguimiento administrativo"],
    responsabilidades: "Trazabilidad de la documentación del proceso.",
    autoridad: "Gestionar tareas administrativas dentro del procedimiento.",
    relInternas: "Compras, Finanzas y áreas solicitantes.",
    relExternas: "Proveedores.",
    indicadores: "Tiempo de respuesta; documentación completa; registros actualizados.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-GER-002", area: "Gerencia General", nivel: "Administrativo",
    cargo: "Asistente de Gerencia", jefe: "Gerente General",
    proposito: "Brindar apoyo administrativo, documental y logístico a la Gerencia General.",
    formacion: "Técnico, tecnólogo o profesional en administración o afín.",
    formacionComp: "Ofimática, protocolo y gestión documental.",
    experiencia: "Experiencia en asistencia administrativa o ejecutiva.",
    compTecnicas: "Agenda, documentación, correspondencia y herramientas ofimáticas.",
    compComportamentales: "Confidencialidad, organización, comunicación y servicio.",
    funciones: ["Gestionar agenda", "Organizar reuniones", "Preparar documentos", "Coordinar correspondencia y apoyo administrativo"],
    responsabilidades: "Manejo adecuado de información y agenda ejecutiva.",
    autoridad: "Coordinar actividades administrativas delegadas.",
    relInternas: "Gerencia, directores y áreas administrativas.",
    relExternas: "Visitantes, proveedores y aliados.",
    indicadores: "Cumplimiento de agenda; tiempos de respuesta; documentación.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-009", area: "Administrativa y Financiera", nivel: "Administrativo",
    cargo: "Analista Documental", jefe: "Director Administrativo y Financiero",
    proposito: "Garantizar organización, actualización, trazabilidad y disponibilidad de la documentación corporativa.",
    formacion: "Gestión documental, Administración o afín.",
    formacionComp: "Archivo, control documental y herramientas digitales.",
    experiencia: "Experiencia en gestión documental.",
    compTecnicas: "Archivo, clasificación, control de versiones y registros.",
    compComportamentales: "Orden, precisión y confidencialidad.",
    funciones: ["Organizar archivos", "Controlar versiones", "Registrar documentos", "Mantener trazabilidad"],
    responsabilidades: "Integridad y disponibilidad documental.",
    autoridad: "Solicitar actualización de documentos vencidos.",
    relInternas: "Todas las áreas.",
    relExternas: "Proveedores documentales cuando corresponda.",
    indicadores: "Documentos actualizados; errores; tiempos de búsqueda.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-010", area: "Administración", nivel: "Administrativo",
    cargo: "Recepcionista", jefe: "Director Administrativo y Financiero",
    proposito: "Gestionar la atención inicial de visitantes, llamadas y comunicaciones de NIVELIA.",
    formacion: "Técnico administrativo, secretariado, servicio al cliente o afín.",
    formacionComp: "Atención al usuario, ofimática y protocolos.",
    experiencia: "Experiencia en recepción o servicio al cliente.",
    compTecnicas: "Atención, llamadas, registro y manejo de correspondencia.",
    compComportamentales: "Servicio, comunicación, cortesía, organización.",
    funciones: ["Atender visitantes", "Recibir llamadas", "Registrar ingresos", "Orientar usuarios", "Gestionar correspondencia"],
    responsabilidades: "Calidad de la atención y correcta gestión de registros de ingreso.",
    autoridad: "Aplicar protocolos de ingreso y escalar novedades.",
    relInternas: "Todas las áreas.",
    relExternas: "Visitantes, proveedores y clientes.",
    indicadores: "Satisfacción; tiempos de atención; registros correctamente diligenciados.",
    modalidad: "Laboral a término indefinido."
  },
  // ============ OPERACIONES ============
  {
    codigo: "NIV-OPE-001", area: "Operaciones", nivel: "Táctico",
    cargo: "Coordinador de Operaciones", jefe: "Director de Operaciones",
    proposito: "Coordinar la ejecución de las actividades operativas de NIVELIA S.A.S., administrando recursos, personal, logística y requerimientos necesarios para garantizar el cumplimiento de las operaciones.",
    formacion: "Ingeniería Industrial, Ingeniería Civil, Administración, Logística o profesión afín.",
    formacionComp: "Gestión de operaciones, logística, gestión de proyectos, seguridad y control operacional.",
    experiencia: "Experiencia en coordinación de operaciones, logística, mantenimiento, instalación o actividades relacionadas.",
    compTecnicas: "Planeación operacional, asignación de recursos, logística, seguimiento de actividades, control de personal y gestión de incidencias.",
    compComportamentales: "Liderazgo, organización, comunicación, resolución de problemas y orientación a resultados.",
    funciones: ["Coordinar actividades operativas", "Asignar recursos y personal", "Supervisar logística", "Coordinar actividades de instalación y mantenimiento", "Hacer seguimiento a la operación", "Gestionar incidencias", "Apoyar la planificación operacional"],
    responsabilidades: "Cumplimiento de la programación operativa, adecuada utilización de recursos, continuidad operacional y coordinación del personal bajo su responsabilidad.",
    autoridad: "Coordinar recursos y personal operativo dentro de las facultades delegadas por la Dirección de Operaciones.",
    relInternas: "Dirección de Operaciones, Coordinación de Proyectos, Ingeniería, Tecnología, Sostenibilidad, Compras y Administración.",
    relExternas: "Contratistas, proveedores, transportistas y clientes cuando corresponda.",
    indicadores: "Cumplimiento operacional; tiempos de respuesta; cumplimiento de programación; incidentes operativos; utilización de recursos.",
    modalidad: "Contrato laboral a término indefinido para funciones permanentes."
  },
  {
    codigo: "NIV-OPE-002", area: "Operaciones", nivel: "Táctico",
    cargo: "Coordinador de Proyectos", jefe: "Director de Operaciones",
    proposito: "Coordinar la planificación, ejecución y seguimiento de los proyectos desarrollados por NIVELIA.",
    formacion: "Ingeniería, Administración, Ingeniería Industrial o afín.",
    formacionComp: "Gestión de proyectos, planificación, costos y riesgos.",
    experiencia: "Experiencia en coordinación de proyectos.",
    compTecnicas: "Planificación, seguimiento, recursos, cronogramas y gestión de riesgos.",
    compComportamentales: "Liderazgo, organización, comunicación y resolución de conflictos.",
    funciones: ["Elaborar planes", "Coordinar recursos", "Hacer seguimiento a cronogramas", "Gestionar reuniones", "Emitir informes", "Escalar riesgos"],
    responsabilidades: "Cumplimiento de objetivos de los proyectos asignados.",
    autoridad: "Coordinar recursos y solicitar acciones correctivas dentro de su ámbito.",
    relInternas: "Todas las direcciones involucradas.",
    relExternas: "Clientes, contratistas y proveedores.",
    indicadores: "Cumplimiento de cronograma; costos; entregables; riesgos.",
    modalidad: "Laboral a término indefinido cuando la coordinación de proyectos sea función permanente."
  },
  {
    codigo: "NIV-OPE-003", area: "Operaciones", nivel: "Profesional",
    cargo: "Residente de Obra", jefe: "Coordinador de Proyectos",
    proposito: "Coordinar técnicamente la ejecución de actividades de obra o instalación en campo.",
    formacion: "Ingeniería Civil, Arquitectura o profesión afín.",
    formacionComp: "Gestión de obra, seguridad y calidad.",
    experiencia: "Experiencia en ejecución y supervisión de obras.",
    compTecnicas: "Control de obra, personal, materiales, avance y documentación.",
    compComportamentales: "Liderazgo, resolución de problemas, comunicación.",
    funciones: ["Coordinar personal", "Supervisar actividades", "Controlar avances", "Revisar calidad", "Gestionar contratistas e informes"],
    responsabilidades: "Cumplimiento técnico y operativo de las actividades en campo.",
    autoridad: "Coordinar cuadrillas y solicitar correcciones.",
    relInternas: "Operaciones, Ingeniería, SST y Calidad.",
    relExternas: "Contratistas, proveedores y clientes.",
    indicadores: "Avance; cumplimiento de cronograma; incidentes; no conformidades.",
    modalidad: "Modalidad laboral acorde con la duración y naturaleza de la obra o labor cuando el cargo esté específicamente ligado a ella."
  },
  {
    codigo: "NIV-OPE-004", area: "Operaciones", nivel: "Táctico/Operativo",
    cargo: "Supervisor de Campo", jefe: "Coordinador de Operaciones",
    proposito: "Supervisar la ejecución de actividades de campo verificando cumplimiento técnico, operativo, documental y de seguridad.",
    formacion: "Ingeniería Civil, Arquitectura, Tecnología o formación afín según alcance.",
    formacionComp: "Supervisión de obra, seguridad, calidad y lectura de planos.",
    experiencia: "Experiencia en supervisión de obras o actividades de instalación.",
    compTecnicas: "Interpretación de planos, control de obra, materiales, seguimiento de avances.",
    compComportamentales: "Liderazgo, comunicación, organización, resolución de problemas.",
    funciones: ["Supervisar personal y contratistas", "Verificar materiales", "Controlar avances", "Revisar planos", "Reportar desviaciones", "Elaborar informes"],
    responsabilidades: "Cumplimiento de condiciones técnicas, de calidad y seguridad durante la ejecución.",
    autoridad: "Solicitar correcciones y detener actividades que presenten condiciones no conformes dentro de su ámbito de responsabilidad.",
    relInternas: "Operaciones, Ingeniería, SST, Calidad.",
    relExternas: "Contratistas, proveedores y clientes en campo.",
    indicadores: "Avance de obra; no conformidades; incidentes; cumplimiento de programación.",
    modalidad: "Laboral; cuando la función esté vinculada específicamente a una obra, podrá utilizarse la modalidad laboral que corresponda a dicha necesidad."
  },
  {
    codigo: "NIV-TEC-001", area: "Operaciones", nivel: "Técnico",
    cargo: "Técnico de Instalación", jefe: "Supervisor de Campo",
    proposito: "Ejecutar actividades de instalación y montaje de los componentes de las soluciones de NIVELIA.",
    formacion: "Técnico o tecnólogo relacionado con instalación, electricidad, mecánica o área afín.",
    formacionComp: "Seguridad, lectura de planos y procedimientos de montaje.",
    experiencia: "Experiencia en instalaciones o montaje.",
    compTecnicas: "Montaje, conexiones, herramientas y pruebas.",
    compComportamentales: "Disciplina, seguridad, trabajo en equipo y responsabilidad.",
    funciones: ["Instalar", "Realizar conexiones", "Efectuar pruebas", "Reportar novedades", "Apoyar desmontajes y ajustes"],
    responsabilidades: "Correcta ejecución de actividades asignadas y cumplimiento de normas de seguridad.",
    autoridad: "Reportar condiciones inseguras o incompatibilidades técnicas.",
    relInternas: "Operaciones, Ingeniería, Tecnología.",
    relExternas: "Contratistas y proveedores en campo.",
    indicadores: "Trabajos aprobados; fallas; tiempo de instalación; incidentes.",
    modalidad: "Laboral; si la necesidad está asociada a una obra/labor determinada, podrá aplicarse la modalidad laboral correspondiente."
  },
  {
    codigo: "NIV-TEC-002", area: "Operaciones", nivel: "Técnico",
    cargo: "Técnico Electromecánico", jefe: "Supervisor de Campo",
    proposito: "Instalar, mantener y diagnosticar sistemas electromecánicos.",
    formacion: "Técnico o tecnólogo electromecánico.",
    formacionComp: "Automatización, mantenimiento y seguridad industrial.",
    experiencia: "Experiencia en sistemas electromecánicos.",
    compTecnicas: "Diagnóstico, montaje, mantenimiento y pruebas.",
    compComportamentales: "Precisión, responsabilidad y resolución de problemas.",
    funciones: ["Instalar equipos", "Realizar mantenimiento", "Diagnosticar fallas", "Ejecutar pruebas"],
    responsabilidades: "Funcionamiento adecuado de los equipos asignados.",
    autoridad: "Reportar fallas y recomendar acciones técnicas.",
    relInternas: "Operaciones, Tecnología, Ingeniería.",
    relExternas: "Proveedores especializados.",
    indicadores: "Fallas; tiempos de mantenimiento; disponibilidad.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-TEC-003", area: "Operaciones", nivel: "Técnico",
    cargo: "Técnico de Mantenimiento", jefe: "Supervisor de Campo",
    proposito: "Ejecutar actividades de mantenimiento preventivo y correctivo de los sistemas e infraestructura.",
    formacion: "Técnico o tecnólogo en mantenimiento, electricidad, mecánica o afín.",
    formacionComp: "Mantenimiento preventivo, seguridad y diagnóstico.",
    experiencia: "Experiencia en mantenimiento.",
    compTecnicas: "Diagnóstico, reparación, inspección y mantenimiento.",
    compComportamentales: "Responsabilidad, disciplina, atención al detalle.",
    funciones: ["Ejecutar mantenimiento", "Realizar inspecciones", "Corregir fallas", "Registrar actividades"],
    responsabilidades: "Disponibilidad y correcta operación de los equipos asignados.",
    autoridad: "Reportar y escalar fallas técnicas.",
    relInternas: "Operaciones, Tecnología, Ingeniería.",
    relExternas: "Proveedores de mantenimiento.",
    indicadores: "Disponibilidad; tiempo de respuesta; fallas recurrentes.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-TEC-004", area: "Operaciones", nivel: "Técnico",
    cargo: "Técnico Eléctrico", jefe: "Supervisor de Campo",
    proposito: "Ejecutar instalaciones, conexiones, pruebas y mantenimiento de componentes eléctricos.",
    formacion: "Técnico o tecnólogo eléctrico.",
    formacionComp: "Seguridad eléctrica, control y mantenimiento.",
    experiencia: "Experiencia en instalaciones eléctricas.",
    compTecnicas: "Instalación, medición, diagnóstico y mantenimiento.",
    compComportamentales: "Precisión, seguridad y responsabilidad.",
    funciones: ["Realizar conexiones", "Instalar componentes", "Ejecutar mediciones", "Diagnosticar fallas", "Apoyar pruebas"],
    responsabilidades: "Seguridad y calidad de las instalaciones eléctricas.",
    autoridad: "Reportar condiciones inseguras y desviaciones técnicas.",
    relInternas: "Operaciones, Tecnología, Ingeniería.",
    relExternas: "Proveedores y técnicos especializados.",
    indicadores: "Fallas; pruebas aprobadas; incidentes; cumplimiento.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-TEC-005", area: "Operaciones", nivel: "Técnico/Apoyo",
    cargo: "Auxiliar Técnico", jefe: "Supervisor de Campo",
    proposito: "Apoyar actividades técnicas, de instalación, mantenimiento y montaje bajo supervisión.",
    formacion: "Formación técnica relacionada con la actividad.",
    formacionComp: "Seguridad, herramientas y procedimientos operativos.",
    experiencia: "Experiencia básica en actividades técnicas u operativas.",
    compTecnicas: "Herramientas, materiales y procedimientos básicos.",
    compComportamentales: "Disciplina, aprendizaje, trabajo en equipo.",
    funciones: ["Trasladar materiales", "Apoyar montaje", "Preparar herramientas", "Colaborar en mantenimiento y limpieza técnica"],
    responsabilidades: "Ejecución segura de las tareas asignadas.",
    autoridad: "Reportar novedades al responsable técnico.",
    relInternas: "Operaciones e Ingeniería.",
    relExternas: "Contratistas de campo cuando corresponda.",
    indicadores: "Cumplimiento de tareas; incidentes; productividad.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-OPE-005", area: "Operaciones", nivel: "Operativo",
    cargo: "Auxiliar Operativo", jefe: "Coordinador de Operaciones",
    proposito: "Apoyar las actividades de operación, montaje, traslado y mantenimiento básico.",
    formacion: "Educación media o formación técnica según actividad.",
    formacionComp: "Seguridad y procedimientos operativos.",
    experiencia: "Experiencia en labores operativas.",
    compTecnicas: "Herramientas, materiales, logística y apoyo en campo.",
    compComportamentales: "Disciplina, responsabilidad, trabajo en equipo.",
    funciones: ["Apoyar montaje", "Trasladar materiales", "Organizar áreas", "Apoyar actividades operativas"],
    responsabilidades: "Ejecución segura y oportuna de tareas asignadas.",
    autoridad: "Reportar novedades y condiciones inseguras.",
    relInternas: "Operaciones, Almacén, Ingeniería.",
    relExternas: "Contratistas de campo.",
    indicadores: "Cumplimiento; productividad; incidentes.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-OPE-006", area: "Operaciones", nivel: "Operativo",
    cargo: "Almacenista", jefe: "Coordinador de Operaciones",
    proposito: "Administrar la recepción, almacenamiento, control y despacho de materiales y equipos.",
    formacion: "Técnico en logística, almacén o afín.",
    formacionComp: "Inventarios y manejo de materiales.",
    experiencia: "Experiencia en almacén o logística.",
    compTecnicas: "Inventarios, almacenamiento, registros y despachos.",
    compComportamentales: "Orden, responsabilidad y precisión.",
    funciones: ["Recibir materiales", "Controlar inventario", "Almacenar", "Preparar despachos", "Registrar movimientos"],
    responsabilidades: "Custodia y exactitud del inventario.",
    autoridad: "Reportar diferencias y rechazar documentos incompletos según procedimiento.",
    relInternas: "Operaciones, Compras, Finanzas.",
    relExternas: "Proveedores y transportistas.",
    indicadores: "Exactitud de inventario; pérdidas; despachos oportunos.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-OPE-007", area: "Operaciones", nivel: "Operativo",
    cargo: "Auxiliar de Almacén", jefe: "Almacenista",
    proposito: "Apoyar la recepción, organización y despacho de materiales y equipos.",
    formacion: "Educación media o formación técnica en logística.",
    formacionComp: "Manipulación de materiales y seguridad.",
    experiencia: "Experiencia básica en almacén.",
    compTecnicas: "Inventario, almacenamiento y despacho.",
    compComportamentales: "Orden, disciplina, trabajo en equipo.",
    funciones: ["Recibir materiales", "Organizar", "Apoyar inventarios", "Preparar despachos"],
    responsabilidades: "Correcta manipulación y organización de materiales.",
    autoridad: "Reportar daños o inconsistencias.",
    relInternas: "Almacén, Operaciones, Compras.",
    relExternas: "Transportistas y proveedores.",
    indicadores: "Exactitud; tiempos de despacho; incidencias.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-OPE-008", area: "Operaciones", nivel: "Operativo",
    cargo: "Conductor", jefe: "Coordinador de Operaciones",
    proposito: "Realizar transporte seguro y oportuno de personal, materiales o equipos.",
    formacion: "Licencia y formación exigible de acuerdo con el vehículo y servicio desempeñado.",
    formacionComp: "Seguridad vial, manejo defensivo y primeros auxilios.",
    experiencia: "Experiencia como conductor según el tipo de servicio.",
    compTecnicas: "Conducción, inspección básica del vehículo y logística.",
    compComportamentales: "Responsabilidad, prudencia y servicio.",
    funciones: ["Transportar personal/materiales", "Realizar inspecciones básicas", "Reportar novedades y mantener documentación"],
    responsabilidades: "Seguridad del transporte y cuidado de vehículos/materiales.",
    autoridad: "Reportar condiciones que impidan un traslado seguro.",
    relInternas: "Operaciones, Almacén y Administración.",
    relExternas: "Proveedores, clientes y autoridades cuando corresponda.",
    indicadores: "Cumplimiento de recorridos; incidentes; mantenimiento.",
    modalidad: "Laboral o servicio especializado, según el modelo operativo de NIVELIA."
  },
  // ============ SERVICIOS ============
  {
    codigo: "NIV-SER-001", area: "Servicios Generales", nivel: "Apoyo",
    cargo: "Auxiliar de Servicios Generales", jefe: "Responsable administrativo",
    proposito: "Mantener las condiciones adecuadas de limpieza, orden e higiene de las instalaciones.",
    formacion: "Educación básica/media; capacitación relacionada con el servicio.",
    formacionComp: "Limpieza, desinfección, manejo de insumos y residuos.",
    experiencia: "Experiencia en servicios generales y limpieza.",
    compTecnicas: "Limpieza, desinfección, manejo de insumos y residuos.",
    compComportamentales: "Responsabilidad, orden, discreción y servicio.",
    funciones: ["Limpiar y desinfectar áreas", "Mantener espacios comunes", "Manejar residuos ordinarios", "Reportar novedades"],
    responsabilidades: "Higiene, orden y adecuada conservación de las áreas asignadas.",
    autoridad: "Reportar deterioros, condiciones inseguras y necesidades de insumos.",
    relInternas: "Administración y todas las áreas.",
    relExternas: "Proveedor de servicios, si se terceriza.",
    indicadores: "Cumplimiento de rutinas; inspecciones; novedades.",
    modalidad: "Laboral o tercerizado, según el modelo operativo."
  },
  {
    codigo: "NIV-SER-002", area: "Servicios Generales", nivel: "Apoyo",
    cargo: "Personal de Mantenimiento Locativo", jefe: "Responsable administrativo",
    proposito: "Atender necesidades de mantenimiento básico y conservación de las instalaciones de NIVELIA.",
    formacion: "Técnico en mantenimiento locativo, construcción, electricidad o afín, según actividad.",
    formacionComp: "Seguridad, mantenimiento preventivo y herramientas.",
    experiencia: "Experiencia en mantenimiento de instalaciones.",
    compTecnicas: "Reparaciones menores, mantenimiento y diagnóstico básico.",
    compComportamentales: "Responsabilidad, servicio y resolución de problemas.",
    funciones: ["Realizar mantenimiento básico", "Atender solicitudes", "Inspeccionar instalaciones", "Reportar fallas mayores"],
    responsabilidades: "Conservación de las instalaciones dentro de su alcance.",
    autoridad: "Recomendar mantenimiento especializado cuando sea necesario.",
    relInternas: "Administración, Operaciones.",
    relExternas: "Proveedores especializados.",
    indicadores: "Solicitudes atendidas; tiempo de respuesta; reincidencia de fallas.",
    modalidad: "Laboral o servicio especializado tercerizado según el modelo operativo."
  },
  {
    codigo: "NIV-SER-003", area: "Servicios de Apoyo", nivel: "Apoyo",
    cargo: "Auxiliar de Cafetería", jefe: "Responsable administrativo",
    proposito: "Proporcionar el servicio básico de cafetería y mantener las condiciones adecuadas del área.",
    formacion: "Educación básica/media; formación relacionada con manipulación de alimentos cuando corresponda.",
    formacionComp: "Higiene, servicio y manipulación de alimentos.",
    experiencia: "Experiencia en cafetería, atención o servicios similares.",
    compTecnicas: "Preparación básica de bebidas, higiene y manejo de insumos.",
    compComportamentales: "Servicio, cordialidad, orden y responsabilidad.",
    funciones: ["Preparar bebidas", "Atender solicitudes", "Organizar el área", "Controlar insumos básicos", "Mantener higiene"],
    responsabilidades: "Calidad del servicio y condiciones higiénicas del área.",
    autoridad: "Reportar necesidades de insumos y condiciones de funcionamiento.",
    relInternas: "Administración y colaboradores.",
    relExternas: "Proveedores de insumos o empresa tercerizada.",
    indicadores: "Disponibilidad de insumos; orden; satisfacción del servicio.",
    modalidad: "Laboral o tercerizado, según el modelo operativo."
  },
  {
    codigo: "NIV-SER-004", area: "Servicios de Apoyo", nivel: "Apoyo",
    cargo: "Personal de Atención", jefe: "Responsable administrativo",
    proposito: "Brindar apoyo en la atención de visitantes, reuniones y servicios internos.",
    formacion: "Educación media o formación técnica en servicio.",
    formacionComp: "Servicio al cliente y protocolo.",
    experiencia: "Experiencia en atención y servicio.",
    compTecnicas: "Atención, protocolo y organización.",
    compComportamentales: "Cortesía, comunicación, disposición de servicio.",
    funciones: ["Atender visitantes", "Apoyar reuniones", "Orientar usuarios", "Organizar espacios de atención"],
    responsabilidades: "Calidad y cordialidad del servicio.",
    autoridad: "Aplicar procedimientos de atención definidos.",
    relInternas: "Todas las áreas.",
    relExternas: "Visitantes, proveedores y clientes.",
    indicadores: "Satisfacción; tiempos de atención; incidencias.",
    modalidad: "Laboral o tercerizado."
  },
  {
    codigo: "NIV-SER-005", area: "Seguridad", nivel: "Servicio Externo",
    cargo: "Servicio de Vigilancia Tercerizado", jefe: "Responsable administrativo",
    proposito: "Garantizar el control de acceso y protección de las instalaciones, personas y bienes de NIVELIA mediante un proveedor especializado.",
    formacion: "A cargo del proveedor conforme a los requisitos legales y contractuales aplicables.",
    formacionComp: "A cargo del proveedor especializado.",
    experiencia: "A cargo del proveedor especializado.",
    compTecnicas: "Control de acceso, vigilancia, manejo de novedades y protocolos de seguridad.",
    compComportamentales: "Atención, disciplina, responsabilidad, confidencialidad.",
    funciones: ["Controlar acceso", "Registrar visitantes", "Realizar vigilancia", "Reportar novedades", "Aplicar protocolos"],
    responsabilidades: "Cumplir las condiciones de seguridad establecidas contractualmente.",
    autoridad: "Aplicar protocolos de acceso y escalar incidentes.",
    relInternas: "Administración y Gerencia.",
    relExternas: "Empresa de vigilancia contratada.",
    indicadores: "Incidentes; cumplimiento de turnos; novedades gestionadas; cumplimiento contractual.",
    modalidad: "Servicio especializado tercerizado."
  },
  {
    codigo: "NIV-SER-EXT-001", area: "Servicios Externos", nivel: "Servicio Especializado",
    cargo: "Gestión de Servicios Especializados Externos", jefe: "Director Administrativo y Financiero",
    proposito: "Gestionar servicios especializados que NIVELIA decida contratar externamente para complementar sus capacidades internas.",
    formacion: "No aplica (servicios externos).",
    formacionComp: "No aplica.",
    experiencia: "Capacidad técnica; experiencia; cumplimiento; calidad; seguridad; costos; requisitos legales.",
    compTecnicas: "Definir requerimientos; seleccionar proveedores; formalizar contratación; supervisar desempeño.",
    compComportamentales: "Cumplimiento de servicio; entregas oportunas; incidencias; no conformidades; desempeño contractual.",
    funciones: ["Vigilancia", "Aseo", "Asesoría jurídica especializada", "Consultoría técnica", "Servicios contables especializados", "Mantenimiento especializado", "Transporte"],
    responsabilidades: "Ejecutar el servicio conforme a las condiciones contractuales y requisitos aplicables.",
    autoridad: "Según contrato.",
    relInternas: "Todas las áreas solicitantes.",
    relExternas: "Proveedores especializados.",
    indicadores: "Cumplimiento de servicio; entregas oportunas; incidencias; no conformidades; desempeño contractual.",
    modalidad: "Contratación de servicios especializados / tercerización según la naturaleza del servicio."
  },
    // ============ PERFILES ADICIONALES (Sección 8) ============
  {
    codigo: "NIV-TI-008", area: "Tecnología e Innovación", nivel: "Técnico",
    cargo: "Técnico de Soporte TI", jefe: "Director de Tecnología e Innovación",
    proposito: "Atender incidentes, requerimientos y soporte básico de infraestructura y equipos tecnológicos.",
    formacion: "Técnico o tecnólogo en Sistemas, Redes o afín.",
    formacionComp: "Soporte, redes, mantenimiento y seguridad básica.",
    experiencia: "Experiencia en soporte técnico.",
    compTecnicas: "Hardware, software, redes, mantenimiento y soporte.",
    compComportamentales: "Servicio, paciencia, comunicación y organización.",
    funciones: ["Atender usuarios", "Instalar equipos", "Diagnosticar incidentes", "Mantener inventarios", "Escalar problemas"],
    responsabilidades: "Continuidad del soporte tecnológico de primer nivel.",
    autoridad: "Escalar incidentes según prioridad y procedimiento.",
    relInternas: "Todas las áreas.",
    relExternas: "Proveedores TI.",
    indicadores: "Tiempo de respuesta; incidentes resueltos; satisfacción del usuario.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-008", area: "Administrativa y Financiera", nivel: "Administrativo",
    cargo: "Auxiliar de Compras", jefe: "Analista / Profesional de Compras",
    proposito: "Apoyar las actividades administrativas y documentales del proceso de compras.",
    formacion: "Técnico administrativo, logística o afín.",
    formacionComp: "Compras y herramientas ofimáticas.",
    experiencia: "Experiencia en apoyo administrativo o compras.",
    compTecnicas: "Cotizaciones, registros, seguimiento y archivo.",
    compComportamentales: "Orden, atención al detalle, responsabilidad.",
    funciones: ["Solicitar cotizaciones", "Organizar ofertas", "Actualizar registros", "Hacer seguimiento administrativo"],
    responsabilidades: "Trazabilidad de la documentación del proceso.",
    autoridad: "Gestionar tareas administrativas dentro del procedimiento.",
    relInternas: "Compras, Finanzas y áreas solicitantes.",
    relExternas: "Proveedores.",
    indicadores: "Tiempo de respuesta; documentación completa; registros actualizados.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-GER-002", area: "Gerencia General", nivel: "Administrativo",
    cargo: "Asistente de Gerencia", jefe: "Gerente General",
    proposito: "Brindar apoyo administrativo, documental y logístico a la Gerencia General.",
    formacion: "Técnico, tecnólogo o profesional en administración o afín.",
    formacionComp: "Ofimática, protocolo y gestión documental.",
    experiencia: "Experiencia en asistencia administrativa o ejecutiva.",
    compTecnicas: "Agenda, documentación, correspondencia y herramientas ofimáticas.",
    compComportamentales: "Confidencialidad, organización, comunicación y servicio.",
    funciones: ["Gestionar agenda", "Organizar reuniones", "Preparar documentos", "Coordinar correspondencia y apoyo administrativo"],
    responsabilidades: "Manejo adecuado de información y agenda ejecutiva.",
    autoridad: "Coordinar actividades administrativas delegadas.",
    relInternas: "Gerencia, directores y áreas administrativas.",
    relExternas: "Visitantes, proveedores y aliados.",
    indicadores: "Cumplimiento de agenda; tiempos de respuesta; documentación.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-009", area: "Administrativa y Financiera", nivel: "Administrativo",
    cargo: "Analista Documental", jefe: "Director Administrativo y Financiero",
    proposito: "Garantizar organización, actualización, trazabilidad y disponibilidad de la documentación corporativa.",
    formacion: "Gestión documental, Administración o afín.",
    formacionComp: "Archivo, control documental y herramientas digitales.",
    experiencia: "Experiencia en gestión documental.",
    compTecnicas: "Archivo, clasificación, control de versiones y registros.",
    compComportamentales: "Orden, precisión y confidencialidad.",
    funciones: ["Organizar archivos", "Controlar versiones", "Registrar documentos", "Mantener trazabilidad"],
    responsabilidades: "Integridad y disponibilidad documental.",
    autoridad: "Solicitar actualización de documentos vencidos.",
    relInternas: "Todas las áreas.",
    relExternas: "Proveedores documentales cuando corresponda.",
    indicadores: "Documentos actualizados; errores; tiempos de búsqueda.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-ADM-010", area: "Administración", nivel: "Administrativo",
    cargo: "Recepcionista", jefe: "Director Administrativo y Financiero",
    proposito: "Gestionar la atención inicial de visitantes, llamadas y comunicaciones de NIVELIA.",
    formacion: "Técnico administrativo, secretariado, servicio al cliente o afín.",
    formacionComp: "Atención al usuario, ofimática y protocolos.",
    experiencia: "Experiencia en recepción o servicio al cliente.",
    compTecnicas: "Atención, llamadas, registro y manejo de correspondencia.",
    compComportamentales: "Servicio, comunicación, cortesía, organización.",
    funciones: ["Atender visitantes", "Recibir llamadas", "Registrar ingresos", "Orientar usuarios", "Gestionar correspondencia"],
    responsabilidades: "Calidad de la atención y correcta gestión de registros de ingreso.",
    autoridad: "Aplicar protocolos de ingreso y escalar novedades.",
    relInternas: "Todas las áreas.",
    relExternas: "Visitantes, proveedores y clientes.",
    indicadores: "Satisfacción; tiempos de atención; registros correctamente diligenciados.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-OPE-005", area: "Operaciones", nivel: "Operativo",
    cargo: "Auxiliar Operativo", jefe: "Coordinador de Operaciones",
    proposito: "Apoyar las actividades de operación, montaje, traslado y mantenimiento básico.",
    formacion: "Educación media o formación técnica según actividad.",
    formacionComp: "Seguridad y procedimientos operativos.",
    experiencia: "Experiencia en labores operativas.",
    compTecnicas: "Herramientas, materiales, logística y apoyo en campo.",
    compComportamentales: "Disciplina, responsabilidad, trabajo en equipo.",
    funciones: ["Apoyar montaje", "Trasladar materiales", "Organizar áreas", "Apoyar actividades operativas"],
    responsabilidades: "Ejecución segura y oportuna de tareas asignadas.",
    autoridad: "Reportar novedades y condiciones inseguras.",
    relInternas: "Operaciones, Almacén, Ingeniería.",
    relExternas: "Contratistas de campo.",
    indicadores: "Cumplimiento; productividad; incidentes.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-OPE-006", area: "Operaciones", nivel: "Operativo",
    cargo: "Almacenista", jefe: "Coordinador de Operaciones",
    proposito: "Administrar la recepción, almacenamiento, control y despacho de materiales y equipos.",
    formacion: "Técnico en logística, almacén o afín.",
    formacionComp: "Inventarios y manejo de materiales.",
    experiencia: "Experiencia en almacén o logística.",
    compTecnicas: "Inventarios, almacenamiento, registros y despachos.",
    compComportamentales: "Orden, responsabilidad y precisión.",
    funciones: ["Recibir materiales", "Controlar inventario", "Almacenar", "Preparar despachos", "Registrar movimientos"],
    responsabilidades: "Custodia y exactitud del inventario.",
    autoridad: "Reportar diferencias y rechazar documentos incompletos según procedimiento.",
    relInternas: "Operaciones, Compras, Finanzas.",
    relExternas: "Proveedores y transportistas.",
    indicadores: "Exactitud de inventario; pérdidas; despachos oportunos.",
    modalidad: "Laboral a término indefinido."
  },
  {
    codigo: "NIV-OPE-007", area: "Operaciones", nivel: "Operativo",
    cargo: "Auxiliar de Almacén", jefe: "Almacenista",
    proposito: "Apoyar la recepción, organización y despacho de materiales y equipos.",
    formacion: "Educación media o formación técnica en logística.",
    formacionComp: "Manipulación de materiales y seguridad.",
    experiencia: "Experiencia básica en almacén.",
    compTecnicas: "Inventario, almacenamiento y despacho.",
    compComportamentales: "Orden, disciplina, trabajo en equipo.",
    funciones: ["Recibir materiales", "Organizar", "Apoyar inventarios", "Preparar despachos"],
    responsabilidades: "Correcta manipulación y organización de materiales.",
    autoridad: "Reportar daños o inconsistencias.",
    relInternas: "Almacén, Operaciones, Compras.",
    relExternas: "Transportistas y proveedores.",
    indicadores: "Exactitud; tiempos de despacho; incidencias.",
    modalidad: "Laboral."
  },
  {
    codigo: "NIV-OPE-008", area: "Operaciones", nivel: "Operativo",
    cargo: "Conductor", jefe: "Coordinador de Operaciones",
    proposito: "Realizar transporte seguro y oportuno de personal, materiales o equipos.",
    formacion: "Licencia y formación exigible de acuerdo con el vehículo y servicio desempeñado.",
    formacionComp: "Seguridad vial, manejo defensivo y primeros auxilios.",
    experiencia: "Experiencia como conductor según el tipo de servicio.",
    compTecnicas: "Conducción, inspección básica del vehículo y logística.",
    compComportamentales: "Responsabilidad, prudencia y servicio.",
    funciones: ["Transportar personal/materiales", "Realizar inspecciones básicas", "Reportar novedades y mantener documentación"],
    responsabilidades: "Seguridad del transporte y cuidado de vehículos/materiales.",
    autoridad: "Reportar condiciones que impidan un traslado seguro.",
    relInternas: "Operaciones, Almacén y Administración.",
    relExternas: "Proveedores, clientes y autoridades cuando corresponda.",
    indicadores: "Cumplimiento de recorridos; incidentes; mantenimiento.",
    modalidad: "Laboral o servicio especializado, según el modelo operativo de NIVELIA."
  },
  {
    codigo: "NIV-SER-001", area: "Servicios Generales", nivel: "Apoyo",
    cargo: "Auxiliar de Servicios Generales", jefe: "Responsable administrativo",
    proposito: "Mantener las condiciones adecuadas de limpieza, orden e higiene de las instalaciones.",
    formacion: "Educación básica/media; capacitación relacionada con el servicio.",
    formacionComp: "Limpieza, desinfección, manejo de insumos y residuos.",
    experiencia: "Experiencia en servicios generales y limpieza.",
    compTecnicas: "Limpieza, desinfección, manejo de insumos y residuos.",
    compComportamentales: "Responsabilidad, orden, discreción y servicio.",
    funciones: ["Limpiar y desinfectar áreas", "Mantener espacios comunes", "Manejar residuos ordinarios", "Reportar novedades"],
    responsabilidades: "Higiene, orden y adecuada conservación de las áreas asignadas.",
    autoridad: "Reportar deterioros, condiciones inseguras y necesidades de insumos.",
    relInternas: "Administración y todas las áreas.",
    relExternas: "Proveedor de servicios, si se terceriza.",
    indicadores: "Cumplimiento de rutinas; inspecciones; novedades.",
    modalidad: "Laboral o tercerizado, según el modelo operativo."
  },
  {
    codigo: "NIV-SER-002", area: "Servicios Generales", nivel: "Apoyo",
    cargo: "Personal de Mantenimiento Locativo", jefe: "Responsable administrativo",
    proposito: "Atender necesidades de mantenimiento básico y conservación de las instalaciones de NIVELIA.",
    formacion: "Técnico en mantenimiento locativo, construcción, electricidad o afín, según actividad.",
    formacionComp: "Seguridad, mantenimiento preventivo y herramientas.",
    experiencia: "Experiencia en mantenimiento de instalaciones.",
    compTecnicas: "Reparaciones menores, mantenimiento y diagnóstico básico.",
    compComportamentales: "Responsabilidad, servicio y resolución de problemas.",
    funciones: ["Realizar mantenimiento básico", "Atender solicitudes", "Inspeccionar instalaciones", "Reportar fallas mayores"],
    responsabilidades: "Conservación de las instalaciones dentro de su alcance.",
    autoridad: "Recomendar mantenimiento especializado cuando sea necesario.",
    relInternas: "Administración, Operaciones.",
    relExternas: "Proveedores especializados.",
    indicadores: "Solicitudes atendidas; tiempo de respuesta; reincidencia de fallas.",
    modalidad: "Laboral o servicio especializado tercerizado según el modelo operativo."
  },
  {
    codigo: "NIV-SER-003", area: "Servicios de Apoyo", nivel: "Apoyo",
    cargo: "Auxiliar de Cafetería", jefe: "Responsable administrativo",
    proposito: "Proporcionar el servicio básico de cafetería y mantener las condiciones adecuadas del área.",
    formacion: "Educación básica/media; formación relacionada con manipulación de alimentos cuando corresponda.",
    formacionComp: "Higiene, servicio y manipulación de alimentos.",
    experiencia: "Experiencia en cafetería, atención o servicios similares.",
    compTecnicas: "Preparación básica de bebidas, higiene y manejo de insumos.",
    compComportamentales: "Servicio, cordialidad, orden y responsabilidad.",
    funciones: ["Preparar bebidas", "Atender solicitudes", "Organizar el área", "Controlar insumos básicos", "Mantener higiene"],
    responsabilidades: "Calidad del servicio y condiciones higiénicas del área.",
    autoridad: "Reportar necesidades de insumos y condiciones de funcionamiento.",
    relInternas: "Administración y colaboradores.",
    relExternas: "Proveedores de insumos o empresa tercerizada.",
    indicadores: "Disponibilidad de insumos; orden; satisfacción del servicio.",
    modalidad: "Laboral o tercerizado, según el modelo operativo."
  },
  {
    codigo: "NIV-SER-004", area: "Servicios de Apoyo", nivel: "Apoyo",
    cargo: "Personal de Atención", jefe: "Responsable administrativo",
    proposito: "Brindar apoyo en la atención de visitantes, reuniones y servicios internos.",
    formacion: "Educación media o formación técnica en servicio.",
    formacionComp: "Servicio al cliente y protocolo.",
    experiencia: "Experiencia en atención y servicio.",
    compTecnicas: "Atención, protocolo y organización.",
    compComportamentales: "Cortesía, comunicación, disposición de servicio.",
    funciones: ["Atender visitantes", "Apoyar reuniones", "Orientar usuarios", "Organizar espacios de atención"],
    responsabilidades: "Calidad y cordialidad del servicio.",
    autoridad: "Aplicar procedimientos de atención definidos.",
    relInternas: "Todas las áreas.",
    relExternas: "Visitantes, proveedores y clientes.",
    indicadores: "Satisfacción; tiempos de atención; incidencias.",
    modalidad: "Laboral o tercerizado."
  },
  {
    codigo: "NIV-SER-005", area: "Seguridad", nivel: "Servicio Externo",
    cargo: "Servicio de Vigilancia Tercerizado", jefe: "Responsable administrativo",
    proposito: "Garantizar el control de acceso y protección de las instalaciones, personas y bienes de NIVELIA mediante un proveedor especializado.",
    formacion: "A cargo del proveedor conforme a los requisitos legales y contractuales aplicables.",
    formacionComp: "A cargo del proveedor especializado.",
    experiencia: "A cargo del proveedor especializado.",
    compTecnicas: "Control de acceso, vigilancia, manejo de novedades y protocolos de seguridad.",
    compComportamentales: "Atención, disciplina, responsabilidad, confidencialidad.",
    funciones: ["Controlar acceso", "Registrar visitantes", "Realizar vigilancia", "Reportar novedades", "Aplicar protocolos"],
    responsabilidades: "Cumplir las condiciones de seguridad establecidas contractualmente.",
    autoridad: "Aplicar protocolos de acceso y escalar incidentes.",
    relInternas: "Administración y Gerencia.",
    relExternas: "Empresa de vigilancia contratada.",
    indicadores: "Incidentes; cumplimiento de turnos; novedades gestionadas; cumplimiento contractual.",
    modalidad: "Servicio especializado tercerizado."
  },
  {
    codigo: "NIV-SER-EXT-001", area: "Servicios Externos", nivel: "Servicio Especializado",
    cargo: "Gestión de Servicios Especializados Externos", jefe: "Director Administrativo y Financiero",
    proposito: "Gestionar servicios especializados que NIVELIA decida contratar externamente para complementar sus capacidades internas.",
    formacion: "No aplica (servicios externos).",
    formacionComp: "No aplica.",
    experiencia: "Capacidad técnica; experiencia; cumplimiento; calidad; seguridad; costos; requisitos legales.",
    compTecnicas: "Definir requerimientos; seleccionar proveedores; formalizar contratación; supervisar desempeño.",
    compComportamentales: "Cumplimiento de servicio; entregas oportunas; incidencias; no conformidades; desempeño contractual.",
    funciones: ["Vigilancia", "Aseo", "Asesoría jurídica especializada", "Consultoría técnica", "Servicios contables especializados", "Mantenimiento especializado", "Transporte"],
    responsabilidades: "Ejecutar el servicio conforme a las condiciones contractuales y requisitos aplicables.",
    autoridad: "Según contrato.",
    relInternas: "Todas las áreas solicitantes.",
    relExternas: "Proveedores especializados.",
    indicadores: "Cumplimiento de servicio; entregas oportunas; incidencias; no conformidades; desempeño contractual.",
    modalidad: "Contratación de servicios especializados / tercerización según la naturaleza del servicio."
  }

];